/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CivitasJuego;
import civitas.Diario;
import civitas.Jugador;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import static civitas.OperacionJuego.AVANZAR;
import controladorCivitas.Respuesta;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class CivitasView extends javax.swing.JFrame {
    
    CivitasJuego juego;
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
    }
    
    void setCivitasJuego(CivitasJuego juego){
        this.juego = juego;
        setVisible(true);
    }
    
    public void actualiza(){
        this.ranking_label.setVisible(false);
        this.ranking.setVisible(false);
        jugadorPanel1.setJugador(juego.getJugadorActual());
        casillaPanel1.setCasilla(juego.getTablero().getCasilla(juego.getJugadorActual().getCasillaActual()));
        
        if(juego.finalDelJuego()){
            this.ranking_label.setVisible(true);
            this.ranking.setVisible(true);
            ArrayList<Jugador> rankingList = new ArrayList<Jugador>();
            rankingList = juego.ranking();
            String ranking = "";
            
            for(int i = 0; i < rankingList.size(); i++)
                ranking = ranking + rankingList.get(i).getNombre() + "\n";
            this.ranking.setText(ranking);
        }
        
        repaint();
        revalidate();
    }
    
    public void pausa(){
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?",
        "Siguiente paso", JOptionPane.YES_NO_OPTION);
        if (val==1) System.exit(0);
 }
    
    public void mostrarSiguienteOperacion(OperacionJuego operacion){
        this.sig_operacion.setText(operacion.toString());
        
        if(operacion == AVANZAR)
            VistaDado.getInstance().createInstance(this);
        
        repaint();
    }
    
    public void mostrarEventos() {
        if (!Diario.getInstance().getEventos().isEmpty())
        new DiarioDialog(this); //crea la ventana del  diario
    }
    
    public Respuesta comprar() {
        int opcion = 1 - JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", 
                JOptionPane.YES_NO_OPTION);
        
        if (opcion == 0) {
            return Respuesta.NO;
        }else{
            return Respuesta.SI;
        }
    }
    
    public OperacionInmobiliaria elegirOperacion(){
        GestionarDialog gestion = new GestionarDialog(this);
        
        switch(gestion.getGestion()){
            case 0 :
                return OperacionInmobiliaria.CONSTRUIR_CASA;
                        
            case 1 :
                return OperacionInmobiliaria.CONSTRUIR_HOTEL;
            
            case 2 :
                return OperacionInmobiliaria.TERMINAR;
            
            default :
                return null;
        }
        
    }
    
    public int elegirPropiedad(){
        PropiedadDialog prop = new PropiedadDialog(this, juego.getJugadorActual());
        
        return prop.getPropiedad();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        casillaPanel1 = new GUI.CasillaPanel();
        jLabel1 = new javax.swing.JLabel();
        sig_operacion = new javax.swing.JTextField();
        ranking_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ranking = new javax.swing.JTextArea();
        jugadorPanel1 = new GUI.JugadorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("JUEGO CIVITAS");

        jLabel1.setText("Siguiente operación: ");

        sig_operacion.setEditable(false);
        sig_operacion.setText("jTextField1");

        ranking_label.setText("jLabel2");

        ranking.setEditable(false);
        ranking.setColumns(20);
        ranking.setRows(5);
        jScrollPane1.setViewportView(ranking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(titulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ranking_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(sig_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(524, 524, 524)
                .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(titulo)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(sig_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ranking_label))))
                .addGap(261, 261, 261))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CasillaPanel casillaPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.JugadorPanel jugadorPanel1;
    private javax.swing.JTextArea ranking;
    private javax.swing.JLabel ranking_label;
    private javax.swing.JTextField sig_operacion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
