/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import civitas.CasillaCalle;
import civitas.Jugador;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author afa
 */
public class PropiedadDialog extends javax.swing.JDialog {

    int PropiedadElegida;
    
    public int getPropiedad(){
        return PropiedadElegida;
    }
    /**
     * Creates new form PropiedadDIalog
     */
    public PropiedadDialog(java.awt.Frame parent, Jugador jugador) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        
        String texto = "";
        
        for (int i = 0; i < jugador.getPropiedades().size(); i++)
            texto = texto + jugador.getPropiedades().get(i) + "\n";
        
        DefaultListModel Propiedad = new DefaultListModel<>(); // datos para la lista
        
        ArrayList<CasillaCalle> opciones = jugador.getPropiedades();
        for (CasillaCalle s: opciones){
            Propiedad.addElement(s.getNombre());}  //se completan los datos
        Propiedades.setModel(Propiedad); //se le dice a la lista cuáles son esos datos
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Propiedades = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Prop.setText("Propiedades:");

        Propiedades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Propiedades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PropiedadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Propiedades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Prop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(Prop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PropiedadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropiedadesMouseClicked
        PropiedadElegida = Propiedades.getSelectedIndex();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_PropiedadesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Prop;
    private javax.swing.JList<String> Propiedades;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
